.PHONY: help init plan apply

help:
	@echo "Auth0 Terraform for web0personal-vector (requires terraform.tfvars or TF_VAR_*)"
	@echo "  make init   - terraform init"
	@echo "  make plan   - terraform plan"
	@echo "  make apply  - terraform apply"

init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply
